### ISSUE TITLE
32-lib libraries required by SimCIty

### ISSUE THREAD

**Issue by gbudny** [tenox7/micropolis#3]
Hi

Does it require 32-libraires on HP-UX 11i-v3 (ia64)?

It informs me about the missing libXpm.so in a directory: /usr/lib/hpux32/dld.so.
It doesn't detect the 64-bit version of this library (Depothelper).

Can you help me?

HP Integrity rx4640
HP-UX 11i-v3 (1905)

**Comment by tenox7** [comment]
interesting, let me check

I'm thinking that perhaps I should integrate libXpm in to the codebase much like tcl/tk/etc

**Comment by tenox7** [comment]
I see the problem, `+DD64` compiler flag is needed...

**Comment by tenox7** [comment]
```
# ldd sim

sim:
        libm.so.1 =>    /usr/lib/hpux64/libm.so.1
        libX11.so.1 =>  /usr/lib/hpux64/libX11.so.1
        libXext.so.1 => /usr/lib/hpux64/libXext.so.1
        libc.so.1 =>    /usr/lib/hpux64/libc.so.1
        libdl.so.1 =>   /usr/lib/hpux64/libdl.so.1
```

**Comment by tenox7** [comment]
ok try this

https://github.com/tenox7/micropolis/releases/download/1.0.0/sim-hpux11iv3-ia64-64

it crashes on my system btw

**Comment by tenox7** [comment]
I also updated the -32 version to use statically linked 32bit Xpm.a let me know if this works

https://github.com/tenox7/micropolis/releases/download/1.0.0/sim-hpux11iv3-ia64-32

**Comment by gbudny** [comment]
Hi

Thank you for the answer.

The previous 32-bit version of SimCity also requires 32 libraries: 

- libiconv.so
- libintl.so

**Comment by tenox7** [comment]
ok I have built a fully 64bit version with libXpm and dependencies statically linked in, it should work now

https://github.com/tenox7/micropolis/releases/download/1.0.0/sim-hpux11iv3-ia64

**Comment by tenox7** [comment]
closing as I was able to verify
feel free to reopen if you still have issue running this
