### ISSUE TITLE
HP-UX 11i-v3 (ia64) - SimCIty can't find 8-bit color or 1-bit monochrome display on: ":0.0".

### ISSUE THREAD

**Issue by gbudny** [tenox7/micropolis#5]
Hi

The 32-bit and 64-bit versions of SimCity don't work because I have this error:

Adding a player on :0.0...
SimCity can't find 8-bit color or 1-bit monochrome display on: ":0.0".
Couldn't add a player on :0.0...
SimCity is exiting because it couldn't connect to any players.

Initially, I thought it was caused by a broken CDE, and I hadn't reinstalled the system yet.
However. the demo version of Dominions: Priests, Prophets, and Pretenders works in a fail-safe session. 

Do you have the same issue with SimCity on HP-UX?

Can you fix it?

**Comment by tenox7** [comment]
for that error try running

```
xhost +
```

**Comment by gbudny** [comment]
Thank you for the answer.

I typed this command before I ran Simcity, but I still see the same error:

Adding a player on :0.0...
SimCity can't find 8-bit color or 1-bit monochrome display on: ":0.0".
Couldn't add a player on :0.0...
SimCity is exiting because it couldn't connect to any players.

**Comment by tenox7** [comment]
can you try this binary:

https://github.com/tenox7/micropolis/releases/download/1.0.0/sim-hpux11iv3-ia64

thanks!

**Comment by gbudny** [comment]
Thank you for the file.

I checked, and I still see the same error.

**Comment by tenox7** [comment]
you may need to change display settings to 8bpp maybe?

**Comment by tenox7** [comment]
are you logging in remotely via xnest, xephyr, reflection or anything like that? or local console?

**Comment by gbudny** [comment]
Thank you for the solution!

I changed two values (ColorDepth) in an XF86Config file from 24 to 8, and SimCity works now.

Can you add this workaround to the README life?
